// <auto-generated />
using System;
using KelimeOyunu.DataAccess.Concrete.ORMEntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KelimeOyunu.DataAccess.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KelimeOyunu.Entity.Kelime", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KelimeUzunluk")
                        .HasColumnType("int");

                    b.Property<DateTime>("SonKullanma")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoruKelime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kelimeler");
                });

            modelBuilder.Entity("KelimeOyunu.Entity.Oturum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArtanSure")
                        .HasColumnType("int");

                    b.Property<DateTime>("OturumSaati")
                        .HasColumnType("datetime2");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<bool>("Sonlandi")
                        .HasColumnType("bit");

                    b.Property<int>("Soru1")
                        .HasColumnType("int");

                    b.Property<int>("Soru10")
                        .HasColumnType("int");

                    b.Property<int>("Soru11")
                        .HasColumnType("int");

                    b.Property<int>("Soru12")
                        .HasColumnType("int");

                    b.Property<int>("Soru13")
                        .HasColumnType("int");

                    b.Property<int>("Soru14")
                        .HasColumnType("int");

                    b.Property<int>("Soru2")
                        .HasColumnType("int");

                    b.Property<int>("Soru3")
                        .HasColumnType("int");

                    b.Property<int>("Soru4")
                        .HasColumnType("int");

                    b.Property<int>("Soru5")
                        .HasColumnType("int");

                    b.Property<int>("Soru6")
                        .HasColumnType("int");

                    b.Property<int>("Soru7")
                        .HasColumnType("int");

                    b.Property<int>("Soru8")
                        .HasColumnType("int");

                    b.Property<int>("Soru9")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Oturumlar");
                });

            modelBuilder.Entity("KelimeOyunu.Entity.Surec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BaslanacakSure")
                        .HasColumnType("datetime2");

                    b.Property<int>("KalanSure")
                        .HasColumnType("int");

                    b.Property<int>("OturumID")
                        .HasColumnType("int");

                    b.Property<string>("Soru10AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru10Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru11AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru11Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru12AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru12Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru13AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru13Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru14AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru14Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru1AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru1Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru2AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru2Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru3AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru3Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru4AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru4Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru5AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru5Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru6AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru6Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru7AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru7Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru8AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru8Durum")
                        .HasColumnType("int");

                    b.Property<string>("Soru9AHa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soru9Durum")
                        .HasColumnType("int");

                    b.Property<string>("SrConnectionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SureDurduruldu")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Surecler");
                });
#pragma warning restore 612, 618
        }
    }
}
